#!/bin/bash

# email writting & the issu with mohamuod (pace and blassing be upon him)
# For research & knowlagede
urls=(
    "https://mail.google.com/mail/u/1/#inbox?compose=CllgCJqbQRXSFWBLGWzXtMhdLGWbZqnhRCtbvFpflqKMvNJRGbqDdvLqdXCdWhrgQnwRVjjkPHL"
    "https://www.google.com/search?q=best+sites+for+networking&sxsrf=AB5stBiVfQ3z3SYJf66hBc2euQlo3sOjNQ%3A1690954694871&ei=xuvJZNfjNNKw2roP742qCA&ved=0ahUKEwjX3qyPob2AAxVSmFYBHe-GCgEQ4dUDCA8&uact=5&oq=best+sites+for+networking&gs_lp=Egxnd3Mtd2l6LXNlcnAiGWJlc3Qgc2l0ZXMgZm9yIG5ldHdvcmtpbmcyBBAAGEcyBBAAGEcyBBAAGEcyBBAAGEcyBBAAGEcyBBAAGEcyBBAAGEcyBBAAGEdIyk1Q7wdY40lwAHgCkAEAmAEAoAEAqgEAuAEDyAEA-AEB-AEC4gMEGAAgQYgGAZAGCA&sclient=gws-wiz-serp"
    "https://medium.com/search?q=open+source+funding"
    "https://medium.com/open-collective"
    "https://medium.com/open-collective/about"
    "https://medium.com/@OpenAtMicrosoft"
    "https://medium.com/?tag=rust"
    "https://dev.to/this-is-learning/chrome-debugger-is-easier-to-use-than-you-might-think-c8"
    "https://app.hackernoon.com/reader"
    "https://www.linkedin.com/feed/"
)

# Path to the Google Chrome executable
chrome="/usr/bin/google-chrome-stable"
xdotool key super+w &
sleep 5 
# Open each URL in a new tab
for url in "${urls[@]}"; do
    "$chrome" --new-tab "$url" &
    sleep 1
done

sleep 1
xdotool key ctrl+1 &
sleep 1
xdotool key ctrl+w &
