#!/bin/bash

########################### For more visit: https://muslimsalat.com/api/#key ##################################
# summary:
# Today times:   (City, country, state)
# https://muslimsalat.com/london.json?key=api_key 

# Weekly times:    (weekly, monthly, yearly)
# https://muslimsalat.com/london/weekly.json?key=api_key 

# Next date weekly times:
# https://muslimsalat.com/london/weekly/12-01-2013.json?key=api_key 

# hours are incremented by 1+:    (True or false)
# https://muslimsalat.com/london/weekly/12-01-2013/true.json?key=api_key 

# which Muslim World League calculation method to use:
# https://muslimsalat.com/london/weekly/12-01-2013/true/5.json?key=api_key 

# Method:
# 1 = Egyptian General Authority of Survey
# 2 = University Of Islamic Sciences, Karachi (Shafi)
# 3 = University Of Islamic Sciences, Karachi (Hanafi)
# 4 = Islamic Circle of North America
# 5 = Muslim World League
# 6 = Umm Al-Qura
# 7 = Fixed Isha

############################################## SUMMARY DOC END ##############################################

# API_URL="https://muslimsalat.com/dhaka.json?key=api_key"
# API_URL="https://muslimsalat.com/dhaka/true/2.json?key=api_key"
API_URL="https://muslimsalat.com/dhaka/2.json?key=api_key"

response=$(curl -s "$API_URL")

if [ -z "$response" ]; then
  echo "Error: Failed to fetch data from the API."
  exit 1
fi

# Parse the response using jq (make sure jq is installed)
prayer_method_name=$(echo "$response" | jq '.prayer_method_name')
city=$(echo "$response" | jq '.city')
date=$(echo "$response" | jq '.items[0].date_for')
fair=$(echo "$response" | jq '.items[0].fajr')
sunrise=$(echo "$response" | jq '.items[0].shurooq')
dhuhr=$(echo "$response" | jq '.items[0].dhuhr')
asr=$(echo "$response" | jq '.items[0].asr')
maghrib=$(echo "$response" | jq '.items[0].maghrib')
isha=$(echo "$response" | jq '.items[0].isha')

# Print the prayer times
echo "'---------+---------+---------+---------+---------+---------+---------'"
echo "Prayer method name: $prayer_method_name "
echo "Today: $date"
echo "City: $city"
echo "Dawn / Fair: $fair 2"
echo "Sunrise: $sunrise"
echo "Forenoon / Dhuhr: $dhuhr OJU"
echo "Declining Afternoon / Asr: $asr OJU"
echo "Sunset / Maghrib: $maghrib 3"
echo "Evening / Isha: $isha OJU - take the mat away"
echo "'---------+---------+---------+---------+---------+---------+---------'"

# Usage: ./script.sh "6:39 pm"
# ./12-24-h $fair
# "${am_pm_part//\"/}"
# ./12-24-h $isha
# "${isha//\"/}"
# ./12-24-h "${isha//\"/}"
# echo "./12-24-h $isha"


time1=$(/home/fahmida/.local/bin/12-24-h "${fair//\"/}")
time2=$(/home/fahmida/.local/bin/12-24-h "${sunrise//\"/}")
time3=$(/home/fahmida/.local/bin/12-24-h "${dhuhr//\"/}")
time4=$(/home/fahmida/.local/bin/12-24-h "${asr//\"/}")
time5=$(/home/fahmida/.local/bin/12-24-h "${maghrib//\"/}")
time6=$(/home/fahmida/.local/bin/12-24-h "${isha//\"/}")


# Get the current date and time in 12-hour format
current_date_12hr=$(date "+%Y-%m-%d %I:%M:%S %p")

# Convert the 12-hour format to 24-hour format
current_date_24hr=$(date -d "$current_date_12hr" "+%H:%M")
# echo "$current_date_24hr"

next_prayer=$(/home/fahmida/.local/bin/most-close-time $current_date_24hr $time1 $time2 $time3 $time4 $time5 $time6)

remaining_time=$(/home/fahmida/.local/bin/calculate_time_difference $current_date_24hr $next_prayer)

# echo "$remaining_time -- $current_date_24hr $next_prayer"


date "+%I:%M %p"
echo ""

if [[ $next_prayer == $time1 ]]
then 
  echo "Upcoming Prayer"
  echo "     Fajr      "
  echo "    ${fair//\"/}      "
elif [[ $next_prayer == $time2 ]]
then
  echo "Upcoming Prayer"
  echo "    Sunrise    "
  echo "    ${sunrise//\"/}      "
elif [[ $next_prayer == $time3 ]]
then
  echo "Upcoming Prayer"
  echo "     Dhuhr     "
  echo "    ${dhuhr//\"/}      "
elif [[ $next_prayer == $time4 ]]
then
  echo "Upcoming Prayer"
  echo "      Asr      "
  echo "    ${asr//\"/}      "
elif [[ $next_prayer == $time5 ]]
then
  echo "Upcoming Prayer"
  echo "    Maghrib    "
  echo "    ${maghrib//\"/}      "
elif [[ $next_prayer == $time6 ]]
then
  echo "Upcoming Prayer"
  echo "     Isha      "
  echo "    ${isha//\"/}      "
else
  echo "non mathch"
fi

/home/fahmida/.local/bin/t $remaining_time && mpv /home/fahmida/.local/bin/cock.mp4















# if [[ $next_prayer == $time1 ]]
# then 
#   echo "Upcoming Prayer"
#   echo "     Fajr      "
#   echo "    $fair      "
# elif [[ $next_prayer == $time2 ]]
# then
#   echo "Upcoming Prayer"
#   echo "    Sunrise    "
#   echo "    $sunrise      "
# elif [[ $next_prayer == $time3 ]]
# then
#   echo "Upcoming Prayer"
#   echo "     Dhuhr     "
#   echo "    $dhuhr      "
# elif [[ $next_prayer == $time4 ]]
# then
#   echo "Upcoming Prayer"
#   echo "      Asr      "
#   echo "    $asr      "
# elif [[ $next_prayer == $time5 ]]
# then
#   echo "Upcoming Prayer"
#   echo "    Maghrib    "
#   echo "    $maghrib      "
# elif [[ $next_prayer == $time6 ]]
# then
#   echo "Upcoming Prayer"
#   echo "     Isha      "
#   echo "    $isha      "
# else
#   echo "non mathch"
# fi
