#!/bin/sh

# If without any argument, display disk space usage for the device in a spcific format.
# awk It prints three columns: filesystem path (column 1), used space (column 3), and available space (column 4).
[ -z "$1" ] && df -h /dev/dm-0 | awk '{print $1 "  " $3 "  " $4 "  " $5}' 

# if the first argument is "a", then checks disk space usage for three devices. 
[ "$1" = "a" ] && df -h /dev/dm-0 /dev/sda3 /dev/sda4 | awk '{print $1 "  " $3 "  " $4 "  " $5}'
