# theme = "jellybeans"
# theme = "ayu_evolve"
# theme = "tokyonight_storm"
theme = "bogster"
# theme = "colibri"

[editor]
# line-number = "absolute"
line-number = "relative"
mouse = false
color-modes = true
auto-save = true
soft-wrap.enable = true
middle-click-paste = false
# rulers = [80, 100]
rulers = [120]
auto-format = true

# [keys.normal."backspace"]
# r = ":run-shell-command cargo run" 
# s = [":w", ":config-reload"]
# c = ":config-open" 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
# character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 1

# [editor.soft-wrap]
# enable = true
# max-wrap = 25 # increase value to reduce forced mid-word wrapping
# max-indent-retain = 0
# wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

#########################################

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "version-control", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

# somethi jj
[keys.insert]
# j = { k = "normal_mode" } # Maps `jk` to exit insert mode.
C-h = "delete_char_backward" # Most terminals do this by default.
C-l = "move_char_right" # Useful to jump over a closing parenthesises.
C-s = ["save_selection", ":w"] # Add `:w` to the default binding.

[keys.normal]
# i = "append_mode"
# a = "insert_mode"
I = "insert_at_line_end"
A = "insert_at_line_start"
s = { s = ":w", f = ":wq"} 
q = { q = ":q!" } 
# s = { f = ":wq"} 
Z = { Z = ":wq" } # Shortcut to save and close buffer.
g = { u = "align_view_top"}
# ";" = "page_cursor_half_up"
t = "page_cursor_half_down"
";" = "page_cursor_half_up"
# "tab-t" = "page_cursor_half_up"
# ";" = "goto_next_function"
# t = "goto_prev_function"
C-h = "delete_char_backward" # Most terminals do this by default.
C-l = "move_char_right" # Useful to jump over a closing parenthesises.
C-s = ["save_selection", ":w"]
C-j = "jump_backward" # C-o is sometimes captured by the "MidnightCommander"
ret = "insert_newline"
y = ["extend_line_below", "yank"]
C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme tokyonight_storm"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
f = "file_picker_in_current_directory"
F = "file_picker"

# create a new minor mode bound to `+`
[keys.normal."="]
t = ":run-shell-command pnpm tauri dev"
# m = ":run-shell-command make"
# c = ":run-shell-command cargo build"
# t = ":run-shell-command cargo test"

